name: Continous Integration
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate and Test
        env:
          GOROOT: ""
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.54.2
          ./bin/golangci-lint run
          go test -v  -coverprofile="coverage.txt" .
          bash <(curl -s https://codecov.io/bash)